/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package santarahotel_managementsystem;

/**
 *
 * @author MyBook Hype AMD
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        button_StatusPesanan = new javax.swing.JButton();
        image_StatusPesanan = new javax.swing.JLabel();
        button_Reservasi = new javax.swing.JButton();
        image_Reservasi = new javax.swing.JLabel();
        button_KamarTersedia = new javax.swing.JButton();
        image_KamarTersedia = new javax.swing.JLabel();
        button_Fasilitas = new javax.swing.JButton();
        image_Fasilitas = new javax.swing.JLabel();
        button_LoginAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setName("mainMenu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(675, 480));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Santara Hotel");
        getContentPane().add(Title);
        Title.setBounds(230, 40, 220, 30);

        button_StatusPesanan.setText("Status Pesanan");
        button_StatusPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_StatusPesananActionPerformed(evt);
            }
        });
        getContentPane().add(button_StatusPesanan);
        button_StatusPesanan.setBounds(170, 190, 120, 30);

        image_StatusPesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/bill.png"))); // NOI18N
        image_StatusPesanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan);
        image_StatusPesanan.setBounds(170, 110, 120, 80);

        button_Reservasi.setText("Reservasi");
        button_Reservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_ReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(button_Reservasi);
        button_Reservasi.setBounds(380, 190, 120, 30);

        image_Reservasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_Reservasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/BOOKING(1).png"))); // NOI18N
        image_Reservasi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_Reservasi);
        image_Reservasi.setBounds(380, 110, 120, 80);

        button_KamarTersedia.setText("Kamar Tersedia");
        button_KamarTersedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_KamarTersediaActionPerformed(evt);
            }
        });
        getContentPane().add(button_KamarTersedia);
        button_KamarTersedia.setBounds(170, 340, 120, 30);

        image_KamarTersedia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_KamarTersedia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/bedroom.png"))); // NOI18N
        image_KamarTersedia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_KamarTersedia);
        image_KamarTersedia.setBounds(170, 260, 120, 80);

        button_Fasilitas.setText("Fasilitas");
        button_Fasilitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_FasilitasActionPerformed(evt);
            }
        });
        getContentPane().add(button_Fasilitas);
        button_Fasilitas.setBounds(380, 340, 120, 30);

        image_Fasilitas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_Fasilitas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/Facility.png"))); // NOI18N
        image_Fasilitas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_Fasilitas);
        image_Fasilitas.setBounds(380, 260, 120, 80);

        button_LoginAdmin.setText("Login Admin");
        button_LoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_LoginAdminActionPerformed(evt);
            }
        });
        getContentPane().add(button_LoginAdmin);
        button_LoginAdmin.setBounds(10, 410, 99, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_LoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LoginAdminActionPerformed
        // TODO add your handling code here:
        MenuLoginAdmin frameLoginAdmin = new MenuLoginAdmin();
        frameLoginAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_LoginAdminActionPerformed

    private void button_StatusPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_StatusPesananActionPerformed
        // TODO add your handling code here:
        MenuStatusPesanan frameStatusPesanan = new MenuStatusPesanan();
        frameStatusPesanan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_StatusPesananActionPerformed

    private void button_ReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_ReservasiActionPerformed
        // TODO add your handling code here:
        MenuReservasi frameReservasi = new MenuReservasi();
        frameReservasi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_ReservasiActionPerformed

    private void button_KamarTersediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_KamarTersediaActionPerformed
        // TODO add your handling code here:
        MenuKamarTersedia frameKamarTersedia = new MenuKamarTersedia();
        frameKamarTersedia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_KamarTersediaActionPerformed

    private void button_FasilitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_FasilitasActionPerformed
        // TODO add your handling code here:
        MenuFasilitas_User frameFasilitas = new MenuFasilitas_User();
        frameFasilitas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_FasilitasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton button_Fasilitas;
    private javax.swing.JButton button_KamarTersedia;
    private javax.swing.JButton button_LoginAdmin;
    private javax.swing.JButton button_Reservasi;
    private javax.swing.JButton button_StatusPesanan;
    private javax.swing.JLabel image_Fasilitas;
    private javax.swing.JLabel image_KamarTersedia;
    private javax.swing.JLabel image_Reservasi;
    private javax.swing.JLabel image_StatusPesanan;
    // End of variables declaration//GEN-END:variables
}
