/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package santarahotel_managementsystem;

/**
 *
 * @author MyBook Hype AMD
 */
public class MenuFasilitas_User extends javax.swing.JFrame {

    /**
     * Creates new form MenuFasilitas_User
     */
    public MenuFasilitas_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jProgressBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();
        jProgressBar3 = new javax.swing.JProgressBar();
        jLabel4 = new javax.swing.JLabel();
        jProgressBar4 = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jProgressBar5 = new javax.swing.JProgressBar();
        jLabel6 = new javax.swing.JLabel();
        jProgressBar6 = new javax.swing.JProgressBar();
        buttonKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(675, 480));
        setMinimumSize(new java.awt.Dimension(675, 480));
        setPreferredSize(new java.awt.Dimension(675, 480));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Fasilitas Kami");
        getContentPane().add(Title);
        Title.setBounds(222, 40, 214, 30);

        jLabel1.setText("★ Kamar Nyaman");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 126, 100, 20);

        jProgressBar1.setValue(80);
        getContentPane().add(jProgressBar1);
        jProgressBar1.setBounds(340, 124, 110, 20);

        jLabel2.setText("★ Kolam Renang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(220, 150, 100, 20);

        jProgressBar2.setValue(90);
        getContentPane().add(jProgressBar2);
        jProgressBar2.setBounds(340, 150, 110, 20);

        jLabel3.setText("★ Sarapan Gratis");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(220, 180, 100, 20);

        jProgressBar3.setValue(70);
        getContentPane().add(jProgressBar3);
        jProgressBar3.setBounds(340, 180, 110, 20);

        jLabel4.setText("★ Ruang Rapat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(220, 210, 100, 20);

        jProgressBar4.setValue(68);
        getContentPane().add(jProgressBar4);
        jProgressBar4.setBounds(340, 210, 110, 20);

        jLabel5.setText("★ Cafe");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(220, 240, 100, 20);

        jProgressBar5.setValue(85);
        getContentPane().add(jProgressBar5);
        jProgressBar5.setBounds(340, 240, 110, 20);

        jLabel6.setText("★ Parkir Aman");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(220, 270, 100, 20);

        jProgressBar6.setValue(100);
        getContentPane().add(jProgressBar6);
        jProgressBar6.setBounds(340, 270, 110, 20);

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali);
        buttonKembali.setBounds(300, 320, 74, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        MainMenu frameMainMenu = new MainMenu();
        frameMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuFasilitas_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuFasilitas_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuFasilitas_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuFasilitas_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuFasilitas_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JProgressBar jProgressBar3;
    private javax.swing.JProgressBar jProgressBar4;
    private javax.swing.JProgressBar jProgressBar5;
    private javax.swing.JProgressBar jProgressBar6;
    // End of variables declaration//GEN-END:variables
}
