/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package santarahotel_managementsystem;

/**
 *
 * @author MyBook Hype AMD
 */
public class MenuReservasi_Konfirmasi extends javax.swing.JFrame {

    /**
     * Creates new form MenuReservasi
     */
    public MenuReservasi_Konfirmasi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        field_nama = new javax.swing.JTextField();
        label_nama1 = new javax.swing.JLabel();
        field_nama1 = new javax.swing.JTextField();
        label_nama2 = new javax.swing.JLabel();
        field_nama2 = new javax.swing.JTextField();
        label_nama3 = new javax.swing.JLabel();
        field_nama3 = new javax.swing.JTextField();
        label_nama4 = new javax.swing.JLabel();
        field_nama4 = new javax.swing.JTextField();
        label_nama5 = new javax.swing.JLabel();
        label_nama6 = new javax.swing.JLabel();
        buttonKonfirmasi = new javax.swing.JButton();
        buttonKembali = new javax.swing.JButton();
        field_nama5 = new javax.swing.JTextField();
        field_nama6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        label_nama7 = new javax.swing.JLabel();
        field_nama7 = new javax.swing.JTextField();
        label_nama8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(675, 480));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Reservasi");
        getContentPane().add(Title);
        Title.setBounds(230, 20, 220, 30);

        label_nama.setText("Nama Lengkap");
        getContentPane().add(label_nama);
        label_nama.setBounds(190, 80, 90, 20);

        field_nama.setEditable(false);
        field_nama.setText("<customer name>");
        field_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namaActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama);
        field_nama.setBounds(340, 80, 160, 22);

        label_nama1.setText("Nomor Kependudukan");
        getContentPane().add(label_nama1);
        label_nama1.setBounds(190, 110, 121, 20);

        field_nama1.setEditable(false);
        field_nama1.setText("000000000000000");
        field_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama1ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama1);
        field_nama1.setBounds(340, 110, 160, 22);

        label_nama2.setText("Jumlah Orang");
        getContentPane().add(label_nama2);
        label_nama2.setBounds(190, 140, 90, 20);

        field_nama2.setEditable(false);
        field_nama2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama2ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama2);
        field_nama2.setBounds(340, 140, 160, 22);

        label_nama3.setText("Tanggal Check In");
        getContentPane().add(label_nama3);
        label_nama3.setBounds(190, 170, 90, 20);

        field_nama3.setEditable(false);
        field_nama3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama3ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama3);
        field_nama3.setBounds(340, 170, 160, 22);

        label_nama4.setText("Tanggal Check Out");
        getContentPane().add(label_nama4);
        label_nama4.setBounds(190, 200, 110, 20);

        field_nama4.setEditable(false);
        field_nama4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama4ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama4);
        field_nama4.setBounds(340, 290, 160, 22);

        label_nama5.setText("Tipe Kamar");
        getContentPane().add(label_nama5);
        label_nama5.setBounds(190, 230, 90, 20);

        label_nama6.setText("Metode Pembayaran");
        getContentPane().add(label_nama6);
        label_nama6.setBounds(190, 320, 110, 20);

        buttonKonfirmasi.setText("Konfirmasi");
        buttonKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKonfirmasiActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKonfirmasi);
        buttonKonfirmasi.setBounds(300, 380, 90, 20);

        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali);
        buttonKembali.setBounds(300, 410, 90, 20);

        field_nama5.setEditable(false);
        field_nama5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama5ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama5);
        field_nama5.setBounds(340, 200, 160, 22);

        field_nama6.setEditable(false);
        field_nama6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama6ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama6);
        field_nama6.setBounds(340, 230, 160, 22);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tunai" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(340, 320, 160, 22);

        label_nama7.setText("Total Harga");
        getContentPane().add(label_nama7);
        label_nama7.setBounds(190, 290, 104, 20);

        field_nama7.setEditable(false);
        field_nama7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_nama7ActionPerformed(evt);
            }
        });
        getContentPane().add(field_nama7);
        field_nama7.setBounds(340, 260, 160, 22);

        label_nama8.setText("Layanan Tambahan");
        getContentPane().add(label_nama8);
        label_nama8.setBounds(190, 260, 104, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void field_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_namaActionPerformed

    private void field_nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama1ActionPerformed

    private void field_nama2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama2ActionPerformed

    private void field_nama3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama3ActionPerformed

    private void field_nama4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama4ActionPerformed

    private void field_nama5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama5ActionPerformed

    private void field_nama6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama6ActionPerformed

    private void field_nama7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_nama7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_nama7ActionPerformed

    private void buttonKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKonfirmasiActionPerformed
        // TODO add your handling code here:
        MenuStatusPesanan_Cari frameKonfirmasi = new MenuStatusPesanan_Cari();
        frameKonfirmasi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKonfirmasiActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        MainMenu frameMainMenu = new MainMenu();
        frameMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buttonKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuReservasi_Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuReservasi_Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuReservasi_Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuReservasi_Konfirmasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuReservasi_Konfirmasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonKonfirmasi;
    private javax.swing.JTextField field_nama;
    private javax.swing.JTextField field_nama1;
    private javax.swing.JTextField field_nama2;
    private javax.swing.JTextField field_nama3;
    private javax.swing.JTextField field_nama4;
    private javax.swing.JTextField field_nama5;
    private javax.swing.JTextField field_nama6;
    private javax.swing.JTextField field_nama7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nama1;
    private javax.swing.JLabel label_nama2;
    private javax.swing.JLabel label_nama3;
    private javax.swing.JLabel label_nama4;
    private javax.swing.JLabel label_nama5;
    private javax.swing.JLabel label_nama6;
    private javax.swing.JLabel label_nama7;
    private javax.swing.JLabel label_nama8;
    // End of variables declaration//GEN-END:variables
}
