/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package santarahotel_managementsystem;

/**
 *
 * @author MyBook Hype AMD
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        button_DataPelanggan = new javax.swing.JButton();
        image_StatusPesanan = new javax.swing.JLabel();
        button_DataKamar = new javax.swing.JButton();
        image_StatusPesanan1 = new javax.swing.JLabel();
        button_TotalPendapatan = new javax.swing.JButton();
        image_StatusPesanan2 = new javax.swing.JLabel();
        button_DataPegawai = new javax.swing.JButton();
        image_StatusPesanan3 = new javax.swing.JLabel();
        button_CatatanTagihan = new javax.swing.JButton();
        image_StatusPesanan4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(675, 480));
        getContentPane().setLayout(null);

        Title.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Santara Hotel");
        getContentPane().add(Title);
        Title.setBounds(230, 40, 220, 30);

        jLabel1.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 70, 220, 18);

        button_DataPelanggan.setText("Data Pelanggan");
        button_DataPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DataPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(button_DataPelanggan);
        button_DataPelanggan.setBounds(100, 190, 120, 30);

        image_StatusPesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/Customer.png"))); // NOI18N
        image_StatusPesanan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan);
        image_StatusPesanan.setBounds(100, 110, 120, 80);

        button_DataKamar.setText("Data Kamar");
        button_DataKamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DataKamarActionPerformed(evt);
            }
        });
        getContentPane().add(button_DataKamar);
        button_DataKamar.setBounds(280, 190, 120, 30);

        image_StatusPesanan1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/bedroom.png"))); // NOI18N
        image_StatusPesanan1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan1);
        image_StatusPesanan1.setBounds(280, 110, 120, 80);

        button_TotalPendapatan.setText("Total Pendapatan");
        button_TotalPendapatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_TotalPendapatanActionPerformed(evt);
            }
        });
        getContentPane().add(button_TotalPendapatan);
        button_TotalPendapatan.setBounds(460, 190, 130, 30);

        image_StatusPesanan2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/income.png"))); // NOI18N
        image_StatusPesanan2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan2);
        image_StatusPesanan2.setBounds(460, 110, 130, 80);

        button_DataPegawai.setText("Data Pegawai");
        button_DataPegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_DataPegawaiActionPerformed(evt);
            }
        });
        getContentPane().add(button_DataPegawai);
        button_DataPegawai.setBounds(210, 330, 120, 30);

        image_StatusPesanan3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/Employee.png"))); // NOI18N
        image_StatusPesanan3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan3);
        image_StatusPesanan3.setBounds(210, 250, 120, 80);

        button_CatatanTagihan.setText("Catatan Tagihan");
        button_CatatanTagihan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_CatatanTagihanActionPerformed(evt);
            }
        });
        getContentPane().add(button_CatatanTagihan);
        button_CatatanTagihan.setBounds(380, 330, 120, 30);

        image_StatusPesanan4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        image_StatusPesanan4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/santarahotel_managementsystem/src/Facility2.png"))); // NOI18N
        image_StatusPesanan4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(image_StatusPesanan4);
        image_StatusPesanan4.setBounds(380, 250, 120, 80);

        jButton1.setText("Kembali ke tampilan pelanggan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(240, 400, 200, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_DataPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DataPelangganActionPerformed
        // TODO add your handling code here:
        MenuDataPelanggan frameDataPelanggan = new MenuDataPelanggan();
        frameDataPelanggan.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_button_DataPelangganActionPerformed

    private void button_DataKamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DataKamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_DataKamarActionPerformed

    private void button_TotalPendapatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_TotalPendapatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_TotalPendapatanActionPerformed

    private void button_DataPegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_DataPegawaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_DataPegawaiActionPerformed

    private void button_CatatanTagihanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_CatatanTagihanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_CatatanTagihanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        MainMenu frameMainMenu = new MainMenu();
        frameMainMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton button_CatatanTagihan;
    private javax.swing.JButton button_DataKamar;
    private javax.swing.JButton button_DataPegawai;
    private javax.swing.JButton button_DataPelanggan;
    private javax.swing.JButton button_TotalPendapatan;
    private javax.swing.JLabel image_StatusPesanan;
    private javax.swing.JLabel image_StatusPesanan1;
    private javax.swing.JLabel image_StatusPesanan2;
    private javax.swing.JLabel image_StatusPesanan3;
    private javax.swing.JLabel image_StatusPesanan4;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
